### ISSUE TITLE
Performance of L2G_BA20_unrolling

### ISSUE THREAD

**Issue by whzyf951620** [xpuoxford/L2G-neurips2021#1]
I run your example code in 'README'.md, and I can only get the pred_gmse_mean: 0.96.
It is far away from '0.0594' reported in your paper.
Is it because of the wrong hyper-parameter?
Can I get your all hyper-parameter?
Thank your very much

**Comment by xpuoxford** [comment]
The hyper-parameters are provided in the file (the default setting). If you just run the lines, there wouldn't be any problem. I'd presume that you've changed some of them? Could you please let me know what hyperparameters you have changed that might lead to the failure of training? 

Also, if you were simply running the lines in README.md and still have such issues, could you provide me with more details and the log file? 

We've just re-tested the lines. There shouldn't be any problems.

**Comment by whzyf951620** [comment]
I have not changed any hyperparameters. This is the result file.
L2G_BA20_unroll20.pt：

epoch_train_gmse [13.860059247910977, 0.7356976115703583, 0.7276950889825821, 0.7165240079164505, 0.7063961482048035, 0.6996688070893288, 0.7137173494696617, 0.7461932626366615, 0.8250792637467385, 0.8364553469419479, 0.768252962827
6825, 0.8256044149398803, 0.5451941379904747, 0.372406630218029, 0.28410531260073185, 0.21673239655792714, 0.16734775178134442, 0.13977463874965906, 0.12633969645947218, 0.11907926734536886, 0.11406184960156679, 0.1100332885235548,
0.10770293436944485, 0.10492105532437562, 0.10365353129804135, 0.10269543193280697, 0.1020985159650445, 0.10202575031667947, 0.10221571907401085, 0.10246193759143353, 0.1028106303140521, 0.10330235715955496, 0.10397861510515213, 0.1
0469218280166387, 0.10432859670370817, 0.10383549753576517, 0.10344822168350219, 0.10291148543357849, 0.10251528214663268, 0.10208779126405716, 0.10182936228811741, 0.10157103605568409, 0.10132573306560516, 0.10121355012059212, 0.10
085340816527605, 0.10051836989820004, 0.14987880796194075, 0.10850274432450532, 0.10226543590426446, 0.10127363115549087, 0.10015368830412626, 0.09976745724678039, 0.09954495247453451, 0.09932053215801716, 0.099144841209054, 0.09894
556153565645, 0.09885419987142086, 0.09858250245451927, 0.09840224981307984, 0.09822194203734398, 0.0980947707220912, 0.09790877614170312, 0.09774078939110041, 0.09763968393206596, 0.09749677944928407, 0.09737026389688254, 0.0972782
7180176973, 0.09711614534258843, 0.09708452988415957, 0.0968607423454523, 0.09687628027051687, 0.09675712432712316, 0.09671746376901864, 0.09666212897747756, 0.09655079454183578, 0.09652323238551616, 0.09637070160359144, 0.096330066
77031516, 0.09625746127218009, 0.09614278007298709, 0.09615738701075316, 0.09608966790139675, 0.09599307790398598, 0.09603096388280391, 0.09590405441820621, 0.0958796751871705, 0.09578686099499464, 0.0958479143679142, 0.095789795666
93306, 0.09567829076200723, 0.09570271156728268, 0.0957075148075819, 0.09555849593132734, 0.09559153851121664, 0.09550108402967453, 0.09549237314611674, 0.09538749504834414, 0.09539529912173748, 0.09532754208892584, 0.09527671482414
007]
epoch_val_gmse [13.860059247910977, 0.7356976115703583, 0.7276950889825821, 0.7165240079164505, 0.7063961482048035, 0.6996688070893288, 0.7137173494696617, 0.7461932626366615, 0.8250792637467385, 0.8364553469419479, 0.76825296282768
25, 0.8256044149398803, 0.5451941379904747, 0.372406630218029, 0.28410531260073185, 0.21673239655792714, 0.16734775178134442, 0.13977463874965906, 0.12633969645947218, 0.11907926734536886, 0.11406184960156679, 0.1100332885235548, 0.
10770293436944485, 0.10492105532437562, 0.10365353129804135, 0.10269543193280697, 0.1020985159650445, 0.10202575031667947, 0.10221571907401085, 0.10246193759143353, 0.1028106303140521, 0.10330235715955496, 0.10397861510515213, 0.104
69218280166387, 0.10432859670370817, 0.10383549753576517, 0.10344822168350219, 0.10291148543357849, 0.10251528214663268, 0.10208779126405716, 0.10182936228811741, 0.10157103605568409, 0.10132573306560516, 0.10121355012059212, 0.1008
5340816527605, 0.10051836989820004, 0.14987880796194075, 0.10850274432450532, 0.10226543590426446, 0.10127363115549087, 0.10015368830412626, 0.09976745724678039, 0.09954495247453451, 0.09932053215801716, 0.099144841209054, 0.0989455
6153565645, 0.09885419987142086, 0.09858250245451927, 0.09840224981307984, 0.09822194203734398, 0.0980947707220912, 0.09790877614170312, 0.09774078939110041, 0.09763968393206596, 0.09749677944928407, 0.09737026389688254, 0.097278271
80176973, 0.09711614534258843, 0.09708452988415957, 0.0968607423454523, 0.09687628027051687, 0.09675712432712316, 0.09671746376901864, 0.09666212897747756, 0.09655079454183578, 0.09652323238551616, 0.09637070160359144, 0.09633006677
031516, 0.09625746127218009, 0.09614278007298709, 0.09615738701075316, 0.09608966790139675, 0.09599307790398598, 0.09603096388280391, 0.09590405441820621, 0.0958796751871705, 0.09578686099499464, 0.0958479143679142, 0.09578979566693
306, 0.09567829076200723, 0.09570271156728268, 0.0957075148075819, 0.09555849593132734, 0.09559153851121664, 0.09550108402967453, 0.09549237314611674, 0.09538749504834414, 0.09539529912173748, 0.09532754208892584, 0.0952767148241400
7]
pred_gmse_mean 0.09660128
pred_gmse_mean_ci 0.003890778886881615
auc_mean 0.9977055120609395
auc_ci 0.00046730844993896135
aps_mean 0.9938160580823661
aps_ci 0.0012667064982871666
layerwise_gmse_mean [1.031851, 0.5562182, 0.38439298, 0.17387655, 0.122645706, 0.117065385, 0.11318632, 0.11045182, 0.10852952, 0.10723281, 0.10662168, 0.10759679, 0.109942675, 0.11008166, 0.10975453, 0.1092057, 0.102968186, 0.09275
663, 0.091639966, 0.09469811]
layerwise_gmse_mean_ci  [0.004152960082529485, 0.05797930825755719, 0.011885555786065096, 0.012321581796419658, 0.007191193617947065, 0.00638526627897606, 0.0060627122774429875, 0.005826882913087194, 0.005633853104071203, 0.00550593
93008986416, 0.005377043012483782, 0.005158158664448072, 0.005418921865658725, 0.005313720730551617, 0.005662043647817741, 0.005647192204801049, 0.005674060456379381, 0.005816401279688845, 0.005754170274939682, 0.005139323220269431]

**Comment by xpuoxford** [comment]
1. The Log shows the pred_gmse_mean is 0.09660128, instead of the "pred_gmse_mean: 0.96" in your first comment. 
2. Also, you are not providing the running log here. This is the log for testing. Please note that, we've run the experiments multiple times to have an average score and confidence interval to report. It seems that you've only run it once. Please note that for the deep learning model, the initial values are randomised. You might want to train one model for multiple times.
